name: Deploy Cloud Function
on:
  workflow_dispatch:
    inputs:
      function_name:
        description: 'Name of the Cloud Function'
        required: true
        default: video-interview-invite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy
        run: |
          cd video-answers/candidate-use-case
          gcloud functions deploy ${{ github.event.inputs.function_name }} \
            --entry-point=videoInterviewInvite \
            --runtime=nodejs20 \
            --trigger-http \
            --allow-unauthenticated \
            --no-gen2 \
            --set-env-vars HIREFLIX_API_KEY=${{ secrets.HIREFLIX_API_KEY }}
